### PR TITLE
desktop file

### PR DESCRIPTION
**Pull request by fiendish**
this works for me

### CODE REVIEW

**Comment by keredson** [comment]
this doesn't work for me, or (more likely) i'm doing it wrong.  if i do `sudo python3 setup.py build install` i would expect to it drop `gnomecast.desktop` into `/usr/local/share/applications/`. (nor `/usr/share/applications/`.) which it doesn't.  am i mistaken?

**Comment by keredson** [comment]
ok, so i'm just ignorant.  `$ pip3 install dist/gnomecast-0.2.7.tar.gz` is the key.  :)  thanks!

**Comment by fiendish** [comment]
I was using also (in the repo dir) "pip3 install . --user" and "sudo pip3
install ." to build and install.

Sorry about the slow response.

**Comment by keredson** [comment]
i find setuptools so infuriating.  so many different recommendations over so many years, it's just a mess.

**Comment by keredson** [comment]
`gnomecast-0.2.8` released.

**Pull request merged**
