### PR TITLE
Small fixes and Windows support

### PR DESCRIPTION
**Pull request by horiakr**
Hello!

I have added instructions to the README.md about running this on Windows and applied a few fixes necessary to get things going on this OS. See the commit descriptions for more.

### CODE REVIEW

**Comment by e-ht** [comment]
I can give this a test on Windows over the weekend!

**Comment by keredson** [comment]
All this looks great, thanks!  I don't have Windows to test, if someone else vouches I'll merge.

**Comment by horiakr** [comment]
Thank you!

@keredson Do you want me to also commit the Visual Studio solution and project files which enable opening this project with the popular Windows IDE Visual Studio. I have created them for myself on VS 2015 - there's an extension needed called 'Python Tools for VS' - the main advantage for me is having the Python debugger nicely integrated into the IDE.

**Comment by e-ht** [comment]
@horiakr I have been unable to commandeer a Windows machine. Hopefully someone else is able to test.

**Pull request closed without merging**
